# Generated by Django 5.1.6 on 2025-02-22 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_alter_order_order_customer_alter_order_order_total'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='order_items',
            new_name='service',
        ),
    ]
