name: Deploy via FTPS

on:
  push:
    branches:
      - main  # Change this to your deployment branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Deploy via FTPS
        uses: lukas-hetzenecker/ftp-deploy-action@v1
        with:
          server: ${{ secrets.SFTP_HOST }}
          username: ${{ secrets.SFTP_USERNAME }}
          password: ${{ secrets.FTPS_PASSWORD }}
          port: 21
          protocol: ftps  # Secure FTPS
          local-dir: "./fuachapchap"  # Adjust this path
          server-dir: "/fuachapchap"  # Adjust this path
          dangerous-clean-slate: false  # Set to true if you want to delete old files
